name: AoC 2021

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Black-ify Code
        uses: jpetrucciani/black-check@master
      - name: Commit back to main
        run: |
            git config --global user.name 'autoblack'
            git config --global user.email 'eng-jole@users.noreply.github.com'
            git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
            git checkout $GITHUB_HEAD_REF
            git commit -am "fixup: Format Python code with Black"
            git push